# Generated by Django 5.1.7 on 2025-03-10 23:51

import core.models
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ingredient_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=functools.partial(core.models.model_image_file_path, *(), **{'model': 'recipe'})),
        ),
    ]
