---

name: Checks

on: [push]

jobs: 
  test-lint: 
    name: Test and Lint
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          password: ${{ secrets.DOKR_PASS }}
        env:
          username: ${{ vars.DOKR_USR }}
          password: ${{ secrets.DOKR_PASS }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker compose run --rm app sh -c "python manage.py test" 
      - name: Lint
        run: docker compose run --rm app sh -c "flake8" 



